name: calendrier_etude
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  syncfusion_flutter_calendar: ^20.2.41
  sqflite: ^2.0.0+4
  path: ^1.8.0
  uuid: ^3.0.7
  sqflite_common_ffi: ^2.0.0+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
