// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMMVDw4PXrxwLbET1q91Vw8kP3InRN08Q',
    appId: '1:520666554418:web:1b46d6ac053e5b3b865c2b',
    messagingSenderId: '520666554418',
    projectId: 'calendrier-etudes-b4438',
    authDomain: 'calendrier-etudes-b4438.firebaseapp.com',
    storageBucket: 'calendrier-etudes-b4438.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsUINkVRldBlPDZWYwqUlYqJejILYB_Q',
    appId: '1:520666554418:android:ef51f40502f6124a865c2b',
    messagingSenderId: '520666554418',
    projectId: 'calendrier-etudes-b4438',
    storageBucket: 'calendrier-etudes-b4438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuY6BcLh_jt8dtuH27-S6TasmcbWJ7Isc',
    appId: '1:520666554418:ios:e2f13074f0095e09865c2b',
    messagingSenderId: '520666554418',
    projectId: 'calendrier-etudes-b4438',
    storageBucket: 'calendrier-etudes-b4438.firebasestorage.app',
    iosBundleId: 'com.example.calendrierEtude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuY6BcLh_jt8dtuH27-S6TasmcbWJ7Isc',
    appId: '1:520666554418:ios:e2f13074f0095e09865c2b',
    messagingSenderId: '520666554418',
    projectId: 'calendrier-etudes-b4438',
    storageBucket: 'calendrier-etudes-b4438.firebasestorage.app',
    iosBundleId: 'com.example.calendrierEtude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMMVDw4PXrxwLbET1q91Vw8kP3InRN08Q',
    appId: '1:520666554418:web:f7119f0466db9806865c2b',
    messagingSenderId: '520666554418',
    projectId: 'calendrier-etudes-b4438',
    authDomain: 'calendrier-etudes-b4438.firebaseapp.com',
    storageBucket: 'calendrier-etudes-b4438.firebasestorage.app',
  );

}